apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsdfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsdfy
  template:
    metadata:
      labels:
        app: dsdfy
    spec:
      containers:
      - image: okteto.dev/dsdfy:latest
        name: dsdfy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "486090ef-e862-4005-9b7f-5e348f893539"
        - name: Vless_Path
          value: "/vle52s"
        - name: Vmess_UUID
          value: "486090ef-e862-4005-9b7f-5e348f893539"
        - name: Vmess_Path
          value: "/vme62s"
        - name: Share_Path
          value: "/v2link"
